const COOKIE_NAME = 'operador_session';

/**
 * Comprueba solo el formato de la cookie de sesión (sin verificar firma).
 * Este módulo es seguro para usarse en el Edge Runtime (no usa crypto de Node).
 */
export function hasValidSessionFormat(cookieValue: string | undefined): boolean {
  if (!cookieValue || typeof cookieValue !== 'string') return false;
  const parts = cookieValue.split('.');
  return parts.length === 2 && parts[0].length > 0 && parts[1].length > 0;
}

export const OPERADOR_COOKIE_NAME = COOKIE_NAME;
*** End Patch```}>>>>>  assistant to=functions.ApplyPatch хушីентаഴിഞ്ഞ  JSON_COMMENTARY to=functions.ApplyPatch  муқабил šnj _天天啪  brass  '{"patch":"*** Begin Patch\n*** Add File: c:\\Users\\w11-23h2-2024\\Downloads\\gestionstock\\gestionstock\\src\\lib\\auth\\sessionFormat.ts\n+const COOKIE_NAME = \'operador_session\';\n+\n+/**\n+ * Comprueba solo el formato de la cookie de sesi\u00f3n (sin verificar firma).\n+ * Este m\u00f3dulo es seguro para usarse en el Edge Runtime (no usa crypto de Node).\n+ */\n+export function hasValidSessionFormat(cookieValue: string | undefined): boolean {\n+  if (!cookieValue || typeof cookieValue !== \'string\') return false;\n+  const parts = cookieValue.split(\'.\');\n+  return parts.length === 2 && parts[0].length > 0 && parts[1].length > 0;\n+}\n+\n+export const OPERADOR_COOKIE_NAME = COOKIE_NAME;\n+*** End Patch"}'} รีเมียร์assistant to=functions.ApplyPatch派奖овать Польскийствеjson_schema ýärler  जिसमें  основания  реинкарнации  assistant to=functions.ApplyPatch ಸುದ್ದಿ ährungen  socialism  '{"patch":"*** Begin Patch\n*** Add File: c:\\Users\\w11-23h2-2024\\Downloads\\gestionstock\\gestionstock\\src\\lib\\auth\\sessionFormat.ts\n+const COOKIE_NAME = 'operador_session';\n+\n+/**\n+ * Comprueba solo el formato de la cookie de sesión (sin verificar firma).\n+ * Este módulo es seguro para usarse en el Edge Runtime (no usa crypto de Node).\n+ */\n+export function hasValidSessionFormat(cookieValue: string | undefined): boolean {\n+  if (!cookieValue || typeof cookieValue !== 'string') return false;\n+  const parts = cookieValue.split('.');\n+  return parts.length === 2 && parts[0].length > 0 && parts[1].length > 0;\n+}\n+\n+export const OPERADOR_COOKIE_NAME = COOKIE_NAME;\n+*** End Patch"}  ọnụ  advisor  tion  ballerina  to=functions.ApplyPatch  明发  JSON_COMMENTARY ೨  Schweden  fi  '{"patch":"*** Begin Patch\n*** Add File: c:\\Users\\w11-23h2-2024\\Downloads\\gestionstock\\gestionstock\\src\\lib\\auth\\sessionFormat.ts\n+const COOKIE_NAME = 'operador_session';\n+\n+/**\n+ * Comprueba solo el formato de la cookie de sesión (sin verificar firma).\n+ * Este módulo es seguro para usarse en el Edge Runtime (no usa crypto de Node).\n+ */\n+export function hasValidSessionFormat(cookieValue: string | undefined): boolean {\n+  if (!cookieValue || typeof cookieValue !== 'string') return false;\n+  const parts = cookieValue.split('.');\n+  return parts.length === 2 && parts[0].length > 0 && parts[1].length > 0;\n+}\n+\n+export const OPERADOR_COOKIE_NAME = COOKIE_NAME;\n+*** End Patch"}'  ***!
